# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.cache/wt} [current_project]
set_property parent.project_path {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/Computer Organization and Design/COD_lab/lab5/inst_rom.coe}}
add_files {{D:/Computer Organization and Design/COD_lab/lab6/Fibonacci.coe}}
read_verilog -library xil_defaultlib {
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/ALU.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/CPU.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/IR_decoder.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/Ins_Reg.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/MUX_3to1.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/MUX_4to1.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/MUX_MEM.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/Mux_write_register.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/PC.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/Reg_ALUaout.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/Reg_MEM.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/RegisterA.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/RegisterB.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/Registers.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/clk_div.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/seg_ctrl.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/state_control.v}
  {D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/new/Multicycle_MIPS_CPU.v}
}
read_ip -quiet {{D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/constrs_1/imports/COD_lab/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Computer Organization and Design/COD_lab/lab6/multicycle_MIPS_CPU/multicycle_MIPS_CPU.srcs/constrs_1/imports/COD_lab/Nexys4DDR_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
