# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(465, 306)
        self.centralwidget = QtWidgets.QWidget(LoginDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ipaddr = QtWidgets.QLineEdit(self.centralwidget)
        self.ipaddr.setGeometry(QtCore.QRect(220, 40, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipaddr.sizePolicy().hasHeightForWidth())
        self.ipaddr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ipaddr.setFont(font)
        self.ipaddr.setAutoFillBackground(False)
        self.ipaddr.setStyleSheet("#D3D3D3")
        self.ipaddr.setObjectName("ipaddr")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.database = QtWidgets.QLineEdit(self.centralwidget)
        self.database.setGeometry(QtCore.QRect(220, 80, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.database.setFont(font)
        self.database.setObjectName("database")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(220, 120, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(220, 160, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LoginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LoginBtn.setGeometry(QtCore.QRect(310, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoginBtn.setFont(font)
        self.LoginBtn.setAutoFillBackground(True)
        self.LoginBtn.setObjectName("LoginBtn")
        LoginDialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginDialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 26))
        self.menubar.setObjectName("menubar")
        LoginDialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginDialog)
        self.statusbar.setObjectName("statusbar")
        LoginDialog.setStatusBar(self.statusbar)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "MainWindow"))
        self.label.setText(_translate("LoginDialog", "Server Address:"))
        self.label_2.setText(_translate("LoginDialog", "Database Name:"))
        self.label_3.setText(_translate("LoginDialog", "Username："))
        self.label_4.setText(_translate("LoginDialog", "Password："))
        self.LoginBtn.setText(_translate("LoginDialog", "Login"))

